# Generated by Django 4.2.8 on 2024-02-27 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections24', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postcode',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('postcode', models.CharField(max_length=8)),
                ('constituency_fk', models.ForeignKey(blank=True, db_column='constituency_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='constituency', to='elections24.constituency')),
            ],
        ),
    ]
